---
- name: make relayer dir
  file:
    path: '/home/{{ ansible_user }}/.relayer/config'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    state: directory

- name: Copy relayer config script with customization
  template:
    src: '{{ target }}.yaml.j2'
    dest: '/home/{{ ansible_user }}/.relayer/config/config.yaml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: create relayer systemd unit
  become: true
  template:
    src: 'relayer.service.j2'
    dest: '/etc/systemd/system/relayer.service'
    owner: root
    group: root
    mode: '644'

# - name: Open relayer telemetry port
#   become: true
#   ufw:
#     rule: allow
#     proto: tcp
#     port: '{{ telemetry_port }}'

- name: start relayer service
  become: true
  systemd:
    name: 'relayer'
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
